name: Deploy to SFTP

on:
  push:
    tags:
      - "v[0-9]*.0.0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run build

      - name: Deploy to SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "dist/*"
          target: "/data/sites/web/tuinstrafamily/subsites/learnkorean.tuinstra.family"
